nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173', 'https://localhost:5173', 'https://project.localhost:5173', 'http://project.localhost:5173', 'http://localhost:5174', 'https://localhost:5174', 'https://project.localhost:5174', 'http://project.localhost:5174']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
        expose_headers: ['Link', 'Content-Disposition']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': 
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
        '^/api/':
            origin_regex: true
            allow_origin: ['http://localhost:5173', 'https://localhost:5173', 'https://project.localhost:5173', 'http://project.localhost:5173', 
                          'http://localhost:5174', 'https://localhost:5174', 'https://project.localhost:5174', 'http://project.localhost:5174',
                          'http://localhost:3000', 'https://localhost:3000', 'http://project.localhost:3000', 'https://project.localhost:3000']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
            expose_headers: ['Link', 'Content-Disposition']
            max_age: 3600
            allow_credentials: true
