vich_uploader:
    db_driver: orm
    
    mappings:
        athlete_profile_image:
            uri_prefix: /uploads/athlete/profile
            upload_destination: '%kernel.project_dir%/public/uploads/athlete/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

