controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api/v1
auth:
    path: /api/v1/auth
    controller: App\Controller\AuthController::login
    methods: [POST]
api_health:
    path: /api/v1/health
    controller: App\Controller\HealthController::health
    methods: [GET]
user_me:
    path: /api/v1/me
    controller: App\Controller\UserController::me
    methods: [GET]